Repository jetstack/jetstack-secure-gcm, pull requests merged in 2021-03, with the labels that each got.

#27 Write the UI instructions in the README
  README.md
  chart/jetstack-secure-gcm/Chart.yaml
  chart/jetstack-secure-gcm/charts/cert-manager-v1.1.0.tgz
  chart/jetstack-secure-gcm/charts/google-cas-issuer/Chart.yaml
  chart/jetstack-secure-gcm/charts/google-cas-issuer/templates/NOTES.txt
  chart/jetstack-secure-gcm/charts/google-cas-issuer/templates/_helpers.tpl
  chart/jetstack-secure-gcm/charts/google-cas-issuer/templates/crds.yaml
  chart/jetstack-secure-gcm/charts/google-cas-issuer/templates/deployment.yaml
  chart/jetstack-secure-gcm/charts/google-cas-issuer/templates/service.yaml
  chart/jetstack-secure-gcm/charts/google-cas-issuer/templates/serviceaccount.yaml
  chart/jetstack-secure-gcm/charts/google-cas-issuer/values.yaml
  chart/jetstack-secure-gcm/charts/preflight/.helmignore
  chart/jetstack-secure-gcm/charts/preflight/Chart.yaml
  chart/jetstack-secure-gcm/charts/preflight/README.md
  chart/jetstack-secure-gcm/charts/preflight/templates/NOTES.txt
  chart/jetstack-secure-gcm/charts/preflight/templates/_helpers.tpl
  chart/jetstack-secure-gcm/charts/preflight/templates/deployment.yaml
  chart/jetstack-secure-gcm/charts/preflight/templates/rbac.yaml
  chart/jetstack-secure-gcm/charts/preflight/templates/serviceaccount.yaml
  chart/jetstack-secure-gcm/charts/preflight/values.yaml
  chart/jetstack-secure-gcm/requirements.lock
  chart/jetstack-secure-gcm/templates/application.yaml
  chart/jetstack-secure-gcm/templates/billing-agent-config.yml
  chart/jetstack-secure-gcm/templates/billing-agent-deployment.yaml
  chart/jetstack-secure-gcm/values.yaml
  docs/TESTING-DEPLOYER.md
  schema.yaml
Labels: lgtm, size/XL

#32 Enable the Container Analysis API to let Google review the project
  docs/TESTING-DEPLOYER.md
Labels: lgtm, size/S

#33 Disable retagging in cloudbuild.yaml due to the licenses requirements
  chart/jetstack-secure-gcm/charts/google-cas-issuer/values.yaml
  cloudbuild.yaml
  docs/TESTING-DEPLOYER.md
Labels: lgtm, size/L

#35 Use jetstack public to build and fix Application wrangling
  .gitignore
  README.md
  chart/jetstack-secure-gcm/charts/cert-manager-v1.1.0.tgz
  chart/jetstack-secure-gcm/charts/cert-manager/Chart.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/README.md
  chart/jetstack-secure-gcm/charts/cert-manager/templates/NOTES.txt
  chart/jetstack-secure-gcm/charts/cert-manager/templates/_helpers.tpl
  chart/jetstack-secure-gcm/charts/cert-manager/templates/cainjector-deployment.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/cainjector-psp-clusterrole.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/cainjector-psp-clusterrolebinding.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/cainjector-psp.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/cainjector-rbac.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/cainjector-serviceaccount.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/crds.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/deployment.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/psp-clusterrole.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/psp-clusterrolebinding.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/psp.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/rbac.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/service.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/serviceaccount.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/servicemonitor.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/webhook-deployment.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/webhook-mutating-webhook.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/webhook-psp-clusterrole.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/webhook-psp-clusterrolebinding.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/webhook-psp.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/webhook-rbac.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/webhook-service.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/webhook-serviceaccount.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/templates/webhook-validating-webhook.yaml
  chart/jetstack-secure-gcm/charts/cert-manager/values.yaml
  chart/jetstack-secure-gcm/charts/google-cas-issuer/templates/_helpers.tpl
  chart/jetstack-secure-gcm/charts/preflight/templates/_helpers.tpl
  chart/jetstack-secure-gcm/templates/application.yaml
  chart/jetstack-secure-gcm/templates/billing-agent-config.yml
  chart/jetstack-secure-gcm/templates/billing-agent-deployment.yaml
  chart/jetstack-secure-gcm/values.yaml
  cloudbuild.yaml
  data-test/schema.yaml
  docs/TESTING-DEPLOYER.md
  schema.yaml
Labels: lgtm, size/XXL

#38 Fix the service name used by the ubbagent
  chart/jetstack-secure-gcm/templates/billing-agent-config.yml
Labels: do-not-merge/hold, lgtm, size/XS

#39 Adjust billing agent heartbeat
  chart/jetstack-secure-gcm/templates/billing-agent-config.yml
Labels: lgtm, size/XS

#40 Fixes for the PR comments in #35
  README.md
  docs/TESTING-DEPLOYER.md
Labels: lgtm, size/L

#43 Fix schema yaml too large
  docs/TESTING-DEPLOYER.md
  schema.yaml
Labels: lgtm, size/S
