Repository jetstack/jetstack-secure-gcm, pull requests merged in 2021-04, with the labels that each got.

#45 Make the preflight deployment green on a fresh deployment
  README.md
  chart/jetstack-secure-gcm/values.yaml
  data-test/schema.yaml
  schema.yaml
Labels: lgtm, size/M

#42 application.yaml: add "notes" and description
  README.md
  chart/jetstack-secure-gcm/templates/application.yaml
  chart/jetstack-secure-gcm/values.yaml
  data-test/schema.yaml
  docs/TESTING-DEPLOYER.md
  schema.yaml
Labels: size/L

#50 Update GCM installation instructions
  README.md
Labels: size/L

#51 Drop namespace keys in YAML sample
  README.md
Labels: size/XS
