Repository jetstack/jetstack-secure-gcm, pull requests merged in 2021-06, with the labels that each got.

#54 Add prerequisite to configure GCP project
  README.md
Labels: size/XS

#46 Add a note about the billing in README
  README.md
  docs/TESTING-DEPLOYER.md
Labels: size/M

#49 Add a cloudbuild for running go-providence-checker on all images
  chart/jetstack-secure-gcm/values.yaml
  cloudbuild-retag-with-licenses.yaml
  schema.yaml
Labels: size/L

#56 The Secret in license.yaml not matching the CLI instructions
  README.md
Labels: lgtm, size/XS

#60 Add a deprecation warning for 1.1 and 1.3
  README.md
Labels: size/S
